---
- hosts: all
  environment: "{{proxy_env}}"
  remote_user: root
  gather_facts: no
  
  tasks:

  - name: Check for Python
    raw: test -e /usr/bin/python
    changed_when: false
    failed_when: false
    register: check_python

  - name: Install Python
    raw: yum -y install python
    when: check_python.rc != 0